ALTER TABLE "Staff"
ADD COLUMN IF NOT EXISTS "skills" TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[],
ADD COLUMN IF NOT EXISTS "location" TEXT,
ADD COLUMN IF NOT EXISTS "isAvailable" BOOLEAN NOT NULL DEFAULT true,
ADD COLUMN IF NOT EXISTS "performanceScore" DOUBLE PRECISION NOT NULL DEFAULT 50,
ADD COLUMN IF NOT EXISTS "workload" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN IF NOT EXISTS "currentWorkload" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN IF NOT EXISTS "latitude" DOUBLE PRECISION,
ADD COLUMN IF NOT EXISTS "longitude" DOUBLE PRECISION,
ADD COLUMN IF NOT EXISTS "shiftStart" TEXT,
ADD COLUMN IF NOT EXISTS "shiftEnd" TEXT,
ADD COLUMN IF NOT EXISTS "capacity" INTEGER NOT NULL DEFAULT 5,
ADD COLUMN IF NOT EXISTS "stressLevel" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN IF NOT EXISTS "lastActiveAt" TIMESTAMP(3);
